name: CI-buildah-ssh

on:
  push:
    branches: [main]
    paths:
      - buildah-ssh/Dockerfile

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - uses: actions/checkout@v3
      - name: Build the Docker images
        run: |
          docker build buildah-ssh --file buildah-ssh/Dockerfile --tag ${{ secrets.DOCKER_HUB_USERNAME }}/buildah-ssh:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/buildah-ssh:latest