name: publish-ci-node-utils

on:
  push:
    tags:
      - v*

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - uses: actions/checkout@v3
      - name: Build the Docker images
        run: |
          docker build node-utils --file node-utils/Dockerfile --tag ${{ secrets.DOCKER_HUB_USERNAME }}/node-utils:${{ steps.get_version.outputs.VERSION }}
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/node-utils:${{ steps.get_version.outputs.VERSION }}